export {default as druid} from './druid.png'
export {default as hunter} from './hunter.png'
export {default as mage} from './mage.png'
export {default as priest} from './priest.png'
export {default as rogue} from './rogue.png'
export {default as shaman} from './shaman.png'
export {default as warlock} from './warlock.png'
export {default as warrior} from './warrior.png'